// Copyright (c) technicianted. All rights reserved.
// Licensed under the MIT License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.11.2
// source: v1/whip.proto

package v1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Register is a message sent from whip client to whip control service.
// It must be the first message in the request.
type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hostname is the client hostname for registration and does not
	// need to match the actual hostname.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// domain is the client domain to be used for registration and does
	// not (and is not recommended) to match the actual domain name.
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	// ports is an array of published ports that the client will accept
	// reverse tunnels to.
	Ports []uint32 `protobuf:"varint,3,rep,packed,name=ports,proto3" json:"ports,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{0}
}

func (x *Register) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Register) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Register) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

// ConnectFailed is a message sent from whip client to service indicating
// that the connection requested has failed locally.
type ConnectFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// connection_iD is the unique connection request ID.
	ConnectionID string `protobuf:"bytes,1,opt,name=connection_iD,json=connectionID,proto3" json:"connection_iD,omitempty"`
	// error_message is an aritrary human readable description of the error.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ConnectFailed) Reset() {
	*x = ConnectFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectFailed) ProtoMessage() {}

func (x *ConnectFailed) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectFailed.ProtoReflect.Descriptor instead.
func (*ConnectFailed) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectFailed) GetConnectionID() string {
	if x != nil {
		return x.ConnectionID
	}
	return ""
}

func (x *ConnectFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Pong is a response message sent by the client in response of a Ping
// request.
type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// sequence is the corresponding ping sequence number.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// ping_timestamp is the time the service sent out the ping.
	PingTimestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=ping_timestamp,json=pingTimestamp,proto3" json:"ping_timestamp,omitempty"`
	// pong_timestamp is the time the client responded with pong.
	PongTimestamp *timestamp.Timestamp `protobuf:"bytes,3,opt,name=pong_timestamp,json=pongTimestamp,proto3" json:"pong_timestamp,omitempty"`
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Pong) GetPingTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.PingTimestamp
	}
	return nil
}

func (x *Pong) GetPongTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.PongTimestamp
	}
	return nil
}

// ConnectionPreamble is a message sent on the newly established tcp connection
// from client to whip service. It tells the service which connection request
// this tcp connection corresponds to.
type ConnectionPreamble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// connection_iD is the unique connection request.
	ConnectionID string `protobuf:"bytes,1,opt,name=connection_iD,json=connectionID,proto3" json:"connection_iD,omitempty"`
}

func (x *ConnectionPreamble) Reset() {
	*x = ConnectionPreamble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionPreamble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPreamble) ProtoMessage() {}

func (x *ConnectionPreamble) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionPreamble.ProtoReflect.Descriptor instead.
func (*ConnectionPreamble) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{3}
}

func (x *ConnectionPreamble) GetConnectionID() string {
	if x != nil {
		return x.ConnectionID
	}
	return ""
}

// RequestStream is the message set from client to service.
type RequestStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Stream:
	//	*RequestStream_Register
	//	*RequestStream_ConnectFailed
	//	*RequestStream_Pong
	Stream isRequestStream_Stream `protobuf_oneof:"stream"`
}

func (x *RequestStream) Reset() {
	*x = RequestStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStream) ProtoMessage() {}

func (x *RequestStream) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStream.ProtoReflect.Descriptor instead.
func (*RequestStream) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{4}
}

func (m *RequestStream) GetStream() isRequestStream_Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (x *RequestStream) GetRegister() *Register {
	if x, ok := x.GetStream().(*RequestStream_Register); ok {
		return x.Register
	}
	return nil
}

func (x *RequestStream) GetConnectFailed() *ConnectFailed {
	if x, ok := x.GetStream().(*RequestStream_ConnectFailed); ok {
		return x.ConnectFailed
	}
	return nil
}

func (x *RequestStream) GetPong() *Pong {
	if x, ok := x.GetStream().(*RequestStream_Pong); ok {
		return x.Pong
	}
	return nil
}

type isRequestStream_Stream interface {
	isRequestStream_Stream()
}

type RequestStream_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type RequestStream_ConnectFailed struct {
	ConnectFailed *ConnectFailed `protobuf:"bytes,2,opt,name=connect_failed,json=connectFailed,proto3,oneof"`
}

type RequestStream_Pong struct {
	Pong *Pong `protobuf:"bytes,3,opt,name=pong,proto3,oneof"`
}

func (*RequestStream_Register) isRequestStream_Stream() {}

func (*RequestStream_ConnectFailed) isRequestStream_Stream() {}

func (*RequestStream_Pong) isRequestStream_Stream() {}

// Connect is a control message sent from service to client to request the
// establishment of a new reverse tcp connection.
type Connect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// connection_iD is a unique identifier of this connection request.
	ConnectionID string `protobuf:"bytes,1,opt,name=connection_iD,json=connectionID,proto3" json:"connection_iD,omitempty"`
	// host is the remote host that the client should establish the tcp connection to.
	Host string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// port is the remote port number that the clinet should establish the tcp connection to.
	Port uint32 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	// local_port is the requested local client port to proxy the tcp connection to.
	LocalPort uint32 `protobuf:"varint,4,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
}

func (x *Connect) Reset() {
	*x = Connect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{5}
}

func (x *Connect) GetConnectionID() string {
	if x != nil {
		return x.ConnectionID
	}
	return ""
}

func (x *Connect) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Connect) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Connect) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

// Ping is a request sent from service to client to measure RTT.
type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// seuqence is the sequence number of this request.
	Sequence uint64 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// ping_timestamp is the time this request was sent.
	PingTimestamp *timestamp.Timestamp `protobuf:"bytes,2,opt,name=ping_timestamp,json=pingTimestamp,proto3" json:"ping_timestamp,omitempty"`
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{6}
}

func (x *Ping) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Ping) GetPingTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.PingTimestamp
	}
	return nil
}

// ResponseStream is the message set from service to client.
type ResponseStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Stream:
	//	*ResponseStream_Connect
	//	*ResponseStream_Ping
	Stream isResponseStream_Stream `protobuf_oneof:"stream"`
}

func (x *ResponseStream) Reset() {
	*x = ResponseStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_whip_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStream) ProtoMessage() {}

func (x *ResponseStream) ProtoReflect() protoreflect.Message {
	mi := &file_v1_whip_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStream.ProtoReflect.Descriptor instead.
func (*ResponseStream) Descriptor() ([]byte, []int) {
	return file_v1_whip_proto_rawDescGZIP(), []int{7}
}

func (m *ResponseStream) GetStream() isResponseStream_Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func (x *ResponseStream) GetConnect() *Connect {
	if x, ok := x.GetStream().(*ResponseStream_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *ResponseStream) GetPing() *Ping {
	if x, ok := x.GetStream().(*ResponseStream_Ping); ok {
		return x.Ping
	}
	return nil
}

type isResponseStream_Stream interface {
	isResponseStream_Stream()
}

type ResponseStream_Connect struct {
	Connect *Connect `protobuf:"bytes,1,opt,name=connect,proto3,oneof"`
}

type ResponseStream_Ping struct {
	Ping *Ping `protobuf:"bytes,2,opt,name=ping,proto3,oneof"`
}

func (*ResponseStream_Connect) isResponseStream_Stream() {}

func (*ResponseStream_Ping) isResponseStream_Stream() {}

var File_v1_whip_proto protoreflect.FileDescriptor

var file_v1_whip_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x77, 0x68, 0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x59, 0x0a, 0x0d, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xa8, 0x01, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d,
	0x70, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x41, 0x0a,
	0x0e, 0x70, 0x6f, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0d, 0x70, 0x6f, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x22, 0x39, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x65, 0x61, 0x6d, 0x62, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0xa1, 0x01, 0x0a, 0x0d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x2a, 0x0a,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x5f, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x6f, 0x6e, 0x67, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22,
	0x75, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x65, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x70, 0x69,
	0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d,
	0x70, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x63, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12,
	0x27, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67,
	0x48, 0x00, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x42, 0x08, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x32, 0x3d, 0x0a, 0x04, 0x57, 0x68, 0x69, 0x70, 0x12, 0x35, 0x0a, 0x08, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x12, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_v1_whip_proto_rawDescOnce sync.Once
	file_v1_whip_proto_rawDescData = file_v1_whip_proto_rawDesc
)

func file_v1_whip_proto_rawDescGZIP() []byte {
	file_v1_whip_proto_rawDescOnce.Do(func() {
		file_v1_whip_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_whip_proto_rawDescData)
	})
	return file_v1_whip_proto_rawDescData
}

var file_v1_whip_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_whip_proto_goTypes = []interface{}{
	(*Register)(nil),            // 0: v1.Register
	(*ConnectFailed)(nil),       // 1: v1.ConnectFailed
	(*Pong)(nil),                // 2: v1.Pong
	(*ConnectionPreamble)(nil),  // 3: v1.ConnectionPreamble
	(*RequestStream)(nil),       // 4: v1.RequestStream
	(*Connect)(nil),             // 5: v1.Connect
	(*Ping)(nil),                // 6: v1.Ping
	(*ResponseStream)(nil),      // 7: v1.ResponseStream
	(*timestamp.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_v1_whip_proto_depIdxs = []int32{
	8, // 0: v1.Pong.ping_timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: v1.Pong.pong_timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: v1.RequestStream.register:type_name -> v1.Register
	1, // 3: v1.RequestStream.connect_failed:type_name -> v1.ConnectFailed
	2, // 4: v1.RequestStream.pong:type_name -> v1.Pong
	8, // 5: v1.Ping.ping_timestamp:type_name -> google.protobuf.Timestamp
	5, // 6: v1.ResponseStream.connect:type_name -> v1.Connect
	6, // 7: v1.ResponseStream.ping:type_name -> v1.Ping
	4, // 8: v1.Whip.Register:input_type -> v1.RequestStream
	7, // 9: v1.Whip.Register:output_type -> v1.ResponseStream
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_v1_whip_proto_init() }
func file_v1_whip_proto_init() {
	if File_v1_whip_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_whip_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionPreamble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_whip_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_whip_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*RequestStream_Register)(nil),
		(*RequestStream_ConnectFailed)(nil),
		(*RequestStream_Pong)(nil),
	}
	file_v1_whip_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*ResponseStream_Connect)(nil),
		(*ResponseStream_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_whip_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_whip_proto_goTypes,
		DependencyIndexes: file_v1_whip_proto_depIdxs,
		MessageInfos:      file_v1_whip_proto_msgTypes,
	}.Build()
	File_v1_whip_proto = out.File
	file_v1_whip_proto_rawDesc = nil
	file_v1_whip_proto_goTypes = nil
	file_v1_whip_proto_depIdxs = nil
}
